[package]
name = "term-snake"
version = "0.1.0"
authors = ["Henrik Melsom <melsom.henrik@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.14.1"
cgmath = "0.17.0"
rand = "0.7.2"
